version: "3.7"

services:
  jupyter:
    image: jupyterlab
    container_name: jupyter
    ports:
      - 8888:8888
      - 4040-4080:4040-4080
    volumes:
      - ./notebooks:/opt/workspace/notebooks/
      - ./data:/opt/workspace/data/

  spark:
    image: bitnami/spark:3.1.1
    hostname: spark
    environment:
      - SPARK_MODE=master
    volumes:
      - ./data:/opt/workspace/data/
    ports:
      - 8181:8080
      - 7077:7077

  spark-worker-1:
    image: bitnami/spark:3.1.1
    environment:    
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/workspace/data/

  spark-worker-2:
    image: bitnami/spark:3.1.1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/workspace/data/